Repository moira-alert/web2.0, pull requests merged in 2020-03, with the labels that each got.

#300 fix: Remove extra parentheses from Notifications page
  src/Containers/NotificationListContainer.jsx
Labels: bug

#292 [FEAT] Trigger and Metric column sorting
  src/Components/PatternList/PatternList.jsx
  src/Components/PatternList/PatternList.less
  src/Containers/PatternListContainer.jsx
Labels: feature

#302 Upgrading React-router 4.x.x to 5.1.2
  .eslintrc.json
  flow-typed/npm/react-router-dom_v4.x.x.js
  flow-typed/npm/react-router-dom_v5.x.x.js
  package.json
  src/Containers/TriggerAddContainer.jsx
  src/Containers/TriggerDuplicateContainer.jsx
  src/Containers/TriggerEditContainer.jsx
  src/pages/trigger-list/trigger-list.jsx
  src/pages/trigger/trigger.jsx
  yarn.lock
Labels: dependencies
